### ISSUE TITLE
Animation appears upside down with `Babel_TrasnEmb_GeoLoss` checkpoint

### ISSUE THREAD

**Issue by felixdivo** [priorMDM/priorMDM#17]
With `python -m sample.double_take --model_path ./save/Babel_TrasnEmb_GeoLoss/model000850000.pt --handshake_size 20 --blend_len 10`, the animation is rendered upside down:

https://github.com/priorMDM/priorMDM/assets/4403130/652b989e-2c5b-417c-963d-701bb70022b3

To change this, I removed the negative sign before the `1.3`:

https://github.com/priorMDM/priorMDM/blob/c0129a76fc6c3d68bbeab9c36595ef23e1e84232/data_loaders/humanml/utils/plot_script.py#L105-L106

Then, the animation floor is a bit weird (it's not in the background any more) but at least it has the correct orientation:

https://github.com/priorMDM/priorMDM/assets/4403130/7e5bfb6d-2354-43d9-82c2-b2f01ee4623f

The problem does not occur with the `my_humanml_trans_enc_512` checkpoint.

**Comment by priorMDM** [comment]
Thanks for that, 
there was indeed bug with the minus sign.
Fixed and committed

**Comment by felixdivo** [comment]
Thank you for 1d2955071769de663c7ca0d7725bcc91fa27eb8c!

But the fact that 

> the animation floor is a bit weird (it's not in the background any more)

is not solved by that, right? I can check in a while if some local change causes it, but I really think this is the case for the unchanged repo too.

So what I mean is that the floor is "on top of" the stick figure, instead of the figure standing on top of the grey plane. You can see this happening when watching the second video clip.

**Comment by felixdivo** [comment]
@priorMDM Do you plan to investigate this?

**Comment by felixdivo** [comment]
This should be reopened as it is not fully solved. 🙃
